<a href="https://colab.research.google.com/github/Shashank2909/Sem-vii/blob/main/ISC/171104001_shashank_exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Exercise 1
data = 5649
x=0
while data>0:
    a=int(data % 10.0)
    x=x*10+a
    data=int(data / 10.0)
print(x)


Exercise-1
9465


In [ ]:
# Strings in python

var1 = 'testing'
var2 = "I am running"

var3 = "Hello! "

print ("var1[0:3]: ", var1[0:3])
print ("var2[1:6]: >", var2[1:6],"<")
print(var3*4)


var1[0:3]:  tes
var2[1:6]: >  am r <
Hello! Hello! Hello! Hello! 


In [ ]:
# EXERCISE 2
print("Name: {} Roll no: {} GATE Rank: {} Percentile: {} " .format('Shashank', 171104001, 1550, 65))

Name: Shashank Roll no: 171104001 GATE Rank: 1550 Percentile: 65 


In [ ]:
# EXERCISE 3
players = ['abc', 'de', 'efg', 'ijk', 'lmn', 'op', 'qq', 'rr']
del players[1:4]
del players[2:3]
print(players)

['abc', 'lmn', 'qq', 'rr']


In [ ]:
#Exercise 4

i = '* * * *'
j = '*     '
k = '      *'
for x in range(8):
    if x==0 or x==7 or x==3:
      print(i)
    elif x==1 or x==2:
      print(j)
    elif x==4 or x==5:  
      print(k)


* * * *
*     
*     
* * * *
      *
      *
* * * *


In [2]:
# EXERCISE 5
import numpy as np
A1 = np.random.random((5,4))
A2 = np.random.random((3,4))

A3 = np.concatenate((A1,A2))

A4 = np.concatenate((A3, np.random.randn(2, 4)))
A4 = np.concatenate((A4, np.random.randn(10, 6)), axis=1)

print('Array A1: \n ' , A1)
print('Transpose of A1: \n ', A1.T)
print('Array A2: \n ' , A2)
print('Transpose of A2: \n ', A2.T)
print('Array A3 (size:-8x4): \n ' , A3)
print('Transpose of A3: \n ', A3.T)
print('Array A4 (size:-10X10): \n ' , A4)
print('Transpose of A4: \n ', A4.T)

Array A1: 
  [[0.79625208 0.83805264 0.3857732  0.96348538]
 [0.68699411 0.5321307  0.58321175 0.18546672]
 [0.11101999 0.57959466 0.34589213 0.61748629]
 [0.88678784 0.46181221 0.34905561 0.5989254 ]
 [0.42050668 0.66962138 0.65128628 0.59767866]]
Transpose of A1: 
  [[0.79625208 0.68699411 0.11101999 0.88678784 0.42050668]
 [0.83805264 0.5321307  0.57959466 0.46181221 0.66962138]
 [0.3857732  0.58321175 0.34589213 0.34905561 0.65128628]
 [0.96348538 0.18546672 0.61748629 0.5989254  0.59767866]]
Array A2: 
  [[0.54508858 0.32829038 0.11786225 0.54678504]
 [0.22546369 0.19126282 0.07784764 0.13148261]
 [0.28737907 0.38748443 0.9497515  0.04300303]]
Transpose of A2: 
  [[0.54508858 0.22546369 0.28737907]
 [0.32829038 0.19126282 0.38748443]
 [0.11786225 0.07784764 0.9497515 ]
 [0.54678504 0.13148261 0.04300303]]
Array A3 (size:-8x4): 
  [[0.79625208 0.83805264 0.3857732  0.96348538]
 [0.68699411 0.5321307  0.58321175 0.18546672]
 [0.11101999 0.57959466 0.34589213 0.61748629]
 [0.88678784

In [2]:
# EXERCISE 6
name = {'Rohit':000, 'Dhoni':000,'Kohli':000,'Ronaldo':000,'Messi':000}

for keys in name:
    name[keys] = input('Enter Hash code: ')
print(name)
second = {name['Rohit']:000, name['Dhoni']:000, name['Kohli']:000,name['Ronaldo']:000,name['Messi']:000}
for keys in second:
    second[keys] = input('Enter Mobile no.: ')
print(second)
n = int(input("Enter the no. of entries: "))
for i in range(0,n):66
    a = input("Enter a new name: ")
    name[a] = int(input("Enter hash value: "))
    second[name[a]] = int(input('Enter mob. no:'))
print(name)
m = int(input("Enter no. of entries to be deleted: "))
for i in range(0,m):
    a = input("Enter name to be deleted: ")
    del(name[a])
print(name)

Enter Hash code: 111
Enter Hash code: 222
Enter Hash code: 333
Enter Hash code: 444
Enter Hash code: 555
{'Rohit': '111', 'Dhoni': '222', 'Kohli': '333', 'Ronaldo': '444', 'Messi': '555'}
Enter Mobile no.: 12
Enter Mobile no.: 23
Enter Mobile no.: 34
Enter Mobile no.: 45
Enter Mobile no.: 56
{'111': '12', '222': '23', '333': '34', '444': '45', '555': '56'}
Enter the no. of entries: 2
Enter a new name: Shashank'
Enter hash value: 666
Enter mob. no:67
Enter a new name: Ajgaonkar
Enter hash value: 777
Enter mob. no:78
{'Rohit': '111', 'Dhoni': '222', 'Kohli': '333', 'Ronaldo': '444', 'Messi': '555', "Shashank'": 666, 'Ajgaonkar': 777}
Enter no. of entries to be deleted: 2
Enter name to be deleted: Rohit
Enter name to be deleted: Dhoni
{'Kohli': '333', 'Ronaldo': '444', 'Messi': '555', "Shashank'": 666, 'Ajgaonkar': 777}
