<a href="https://colab.research.google.com/github/Shashank2909/Sem-vii/blob/main/ANN/Pocket_y_hopfield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


w = np.array([1, -1, 0, 0.5])
C = 0.1
D = [-1, -1, 1]
X = np.array([
    [ 1.0, -2.0,  0.0, -1.0],
    [ 0.0,  1.5, -0.5, -1.0],
    [-1.0,  1.0,  0.5, -1.0]
])

pocket = w
run_length = 0
best_run_length = 0

def f(net):
    return 2 * (net > 0) -1

for epoch in range(5):
    print('\nepoch #', epoch+1)
    for x, d in zip(X, D):
        r = d - f(w.T @ x)
        if r == 0:
            run_length += 1
        if r != 0:
            if run_length > best_run_length:
                best_run_length = run_length
                pocket = w.copy()
            w += C * r * x
            run_length = 0
        print(w,'run length:', run_length)
    print('pocket:', pocket)
for x, d in zip(X, D):
    print(f'\ninput: {x} f(net)={f(w.T @ x)} d={d}')



epoch # 1
[ 0.8 -0.6  0.   0.7] run length: 0
[ 0.8 -0.6  0.   0.7] run length: 1
[ 0.6 -0.4  0.1  0.5] run length: 0
pocket: [ 0.8 -0.6  0.   0.7]

epoch # 2
[4.00000000e-01 5.55111512e-17 1.00000000e-01 7.00000000e-01] run length: 0
[4.00000000e-01 5.55111512e-17 1.00000000e-01 7.00000000e-01] run length: 1
[0.2 0.2 0.2 0.5] run length: 0
pocket: [ 0.8 -0.6  0.   0.7]

epoch # 3
[0.2 0.2 0.2 0.5] run length: 1
[0.2 0.2 0.2 0.5] run length: 2
[5.55111512e-17 4.00000000e-01 3.00000000e-01 3.00000000e-01] run length: 0
pocket: [0.2 0.2 0.2 0.5]

epoch # 4
[5.55111512e-17 4.00000000e-01 3.00000000e-01 3.00000000e-01] run length: 1
[5.55111512e-17 1.00000000e-01 4.00000000e-01 5.00000000e-01] run length: 0
[-0.2  0.3  0.5  0.3] run length: 0
pocket: [0.2 0.2 0.2 0.5]

epoch # 5
[-0.2  0.3  0.5  0.3] run length: 1
[-0.2  0.3  0.5  0.3] run length: 2
[-0.2  0.3  0.5  0.3] run length: 3
pocket: [0.2 0.2 0.2 0.5]

input: [ 1. -2.  0. -1.] f(net)=-1 d=-1

input: [ 0.   1.5 -0.5 -1. ] f(net)=-

In [2]:
import numpy as np

def sign(net):
    return 2 * (net >= 0) -1

X = np.array([
    [ 1,  1,  1, -1],
    [-1, -1, -1,  1],
    [ 1,  1,  1,  1],
    [ 1,  1, -1, -1],
    [ 1, -1,  1, -1],
    [-1,  1,  1, -1]
])

n = len(X[0])
P = len(X)
W = np.zeros((n, n))

def sign(net):
    return 2 * (net > 0) -1

for i in range(n):
    for j in range(n):
        W[i, j] = np.sum(X[:, i] * X[:, j]) / P

I = np.random.uniform(-1, 1, (10, 4))
print('stored vectors:\n', X)
for i in I:
    print('\ninput:', i)
    o = i
    while o not in X:
        o = sign(W @ o)
    print('output:', o)

stored vectors:
 [[ 1  1  1 -1]
 [-1 -1 -1  1]
 [ 1  1  1  1]
 [ 1  1 -1 -1]
 [ 1 -1  1 -1]
 [-1  1  1 -1]]

input: [-0.35835058  0.88745483 -0.17174267  0.27872111]
output: [-1  1 -1  1]

input: [-0.30825935 -0.55237565  0.44424953 -0.82444209]
output: [-1 -1  1 -1]

input: [-0.28136525  0.77922905  0.79181421 -0.59562622]
output: [ 1  1  1 -1]

input: [ 0.78412218  0.38610726 -0.16826201  0.51569274]
output: [1 1 1 1]

input: [-0.33583058 -0.28947906 -0.92323059 -0.00183502]
output: [-1 -1 -1  1]

input: [ 0.81776902  0.10954764  0.46028116 -0.96007779]
output: [ 1  1  1 -1]

input: [-0.97169392 -0.29946806 -0.73838421  0.78743095]
output: [-1 -1 -1  1]

input: [-0.4868693   0.09016391  0.64770956 -0.76205865]
output: [ 1  1  1 -1]

input: [ 0.29267071  0.32715369  0.43334201 -0.94786921]
output: [ 1  1  1 -1]

input: [-0.25666791 -0.5721559   0.8652713  -0.45946916]
output: [-1 -1  1 -1]
